name: Sentinel DevSecOps Destroy

on:
  workflow_dispatch:  # Manual trigger only

permissions:
  id-token: write
  contents: read

jobs:
  destroy-infrastructure:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform  # Set default directory for all steps
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::184515318701:role/github-terraform-role
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init

      - name: Destroy infrastructure
        run: terraform destroy -auto-approve
        env:
          TF_VAR_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
